[package]
name = "game"
version = "0.1.0"
authors = ["William Lundstedt <bananavice@gmail.com>"]

[workspace]
members = [
    "./lib/js/",
    "./lib/platform/",
    "./lib/platform_web/",
    "./bin/",
]

[dependencies]
platform = { path = "./lib/platform/" }
assets = { path = "./lib/assets/" }
js = { path = "./lib/js/", optional = true }
platform_web = { path = "./lib/platform_web/", optional = true }
platform_native = { path = "./lib/platform_native/", optional = true }

[features]
build-web = ["js", "platform_web"]
build-native = ["platform_native"]

[[bin]]         
name = "client-native"    
required-features = ["build-native"]

[[bin]]
name = "client-web"
required-features = ["build-web"]